# Generated by Django 5.1.4 on 2024-12-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='recipecategory',
            options={'verbose_name': 'Категория рецепта', 'verbose_name_plural': 'Категории рецептов'},
        ),
        migrations.AlterUniqueTogether(
            name='recipecategory',
            unique_together={('recipe', 'category')},
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(through='recipes.RecipeCategory', to='recipes.category', verbose_name='Категории'),
        ),
        migrations.RemoveField(
            model_name='recipecategory',
            name='author',
        ),
    ]
